### ISSUE TITLE
Examples link is broken

### ISSUE THREAD

**Issue by rafaelalmeida** [sciurius/playtab#1]
Should be https://www.vromans.org/johan/software/sw_playtab.html (currently ends with `sw\_playtab.html`).

Tried to edit or submit a pull request, but GitHub apparently does not support that.

**Comment by sciurius** [comment]
Thanks, fixed.
The docs is a wiki, you should have been able to edit it.

**Comment by rafaelalmeida** [comment]
Thanks a lot!

Yep, tried that as well, but it seems that one can only edit wikis on their own repositories (or at least commit permissions, maybe?). The "Edit" and "New Page" buttons mentioned in the GitHub docs just don't appear for me.

**Comment by sciurius** [comment]
Ah, I see. Access is restricted to users that already have collaborated in the project. Makes sense, in a way.
